import os

BACKEND_URL = os.getenv("BASE_BACKEND_URL", "http://backend:8000")
BACKEND_WEBSOCKET_URL = os.getenv("BASE_BACKEND_WEBSOCKET_URL", "ws://localhost:8000")
MAX_WEBSOCKET_RETRIES = int(os.getenv("MAX_WEBSOCKET_RETRIES", 3))
TIME_BETWEEN_WEBSOCKET_RETRIES = int(os.getenv("TIME_BETWEEN_WEBSOCKET_RETRIES", 5))
REAL_TIME_CHART_REFRESH_INTERVAL = float(os.getenv("PRICE_WEBSOCKET_INTERVAL", 0.01))
DEFAULT_LAST_MINUTES = int(os.getenv("DEFAULT_LAST_MINUTES", 10))
