import os

BACKEND_URL = os.getenv("BASE_BACKEND_URL", "http://backend:8000")
BACKEND_WEBSOCKET_URL = os.getenv("BASE_BACKEND_WEBSOCKET_URL", "ws://localhost:8000")
REAL_TIME_CHART_REFRESH_INTERVAL = float(os.getenv("PRICE_WEBSOCKET_INTERVAL", 0.01))
DEFAULT_LAST_MINUTES = int(os.getenv("DEFAULT_LAST_MINUTES", 10))
